---
title: "CP2602"
output: html_document
---

```{r}
# load libraries 
library(tidyverse)
library(dplyr)
library(janitor)
library(lubridate)
library(readr)
library(stringr)
library(ggplot2)
library(RColorBrewer)

```

```{r}

CP2602_test <- read_csv("data/CP2602_plinazolin_evaluation/CP2602_test.csv")
View(CP2602_test)















```


```{r}


CP2601_test <- rcbd_design %>% 
  mutate(experiment = "CP2601",
         location = "PDREC-F20",
         plot_name = paste(experiment, plot, sep = "_"),
         block = range,
         sort = c(1:60)) %>% 
  rename(accession_name = accession,
         plot_number = plot) %>% 
  select(experiment,
         location,
         accession_name,
         plot_name,
         plot_number,
         block,
         range,
         row,
         sort)

# Write out the file
# write.csv(CP2601_FBF, "data/Cp2601/CP2601_FBF.csv",row.names = FALSE, na = "")

```


```{r, echo=FALSE, fig.width=4, fig.height= 7}

FBF <- CP2602_test

trt.map <- 
  ggplot(FBF, aes(x = row, y = range)) +
  geom_tile(aes(fill = as.factor(range)), color = "black") +  
  geom_text(aes(label = treatment), size = 5, color = "black", angle = 90) +  
  scale_fill_brewer(palette = "Dark2", name = "Block") +  
  scale_y_reverse(breaks = unique(FBF$range)) +  # Flip y-axis and show all row labels
  scale_x_continuous(breaks = unique(FBF$row)) +  # Ensure all range labels are shown
  theme_classic() +
  labs(
    title = "Field Map: CP2602",
    x = "Row",
    y = "Range"
  ) +
  theme(legend.position = "bottom")  # Place the legend at the bottom

plot.map <- 
  ggplot(FBF, aes(x = row, y = range)) +
  geom_tile(aes(fill = as.factor(treatment)), color = "black") +  
  geom_text(aes(label = plot_number), size = 5, color = "black", angle = 90) +  
  scale_fill_brewer(palette = "Dark2", name = "Treatement") +  
  scale_y_reverse(breaks = unique(FBF$range)) +  # Flip y-axis and show all row labels
  scale_x_continuous(breaks = unique(FBF$row)) +  # Ensure all range labels are shown
  theme_classic() +
  labs(
    title = "Field Map: CP2602",
    x = "Row",
    y = "Range"
  ) +
  theme(legend.position = "bottom",
        axis.text = element_text(size = 10, color = "Black"))  # Place the legend at the bottom


```

### trt map
```{r,echo=FALSE}
plot(trt.map)

# ggsave("~/Documents/GitHub/cowpeas/data/CP2602_plinazolin_evaluation/CP2602_trt_map.png", plot = trt.map, width = 9, height = 9, dpi = 300, units = "in")

```

### Plot map
```{r,echo=FALSE}
plot(plot.map)

# ggsave("~/Documents/GitHub/cowpeas/data/CP2602_plinazolin_evaluation/CP2602_plot_map.png", plot = plot.map, width = 9, height = 6, dpi = 300, units = "in")
```
