---
title: "CP2601"
output: html_document
---

```{r}
# load libraries 
library(tidyverse)
library(dplyr)
library(janitor)
library(lubridate)
library(readr)
library(stringr)
library(ggplot2)
library(RColorBrewer)
```

```{r}
geno <- read_csv("data/CP2601/accessions_list.csv")

set.seed(123)  # for reproducibility

# Make sure you have a column with accession names
# Replace 'accession' with your actual column name if different
accessions <- geno$accession_name

# Create blocks (ranges)
blocks <- 1:4

# Generate RCBD
rcbd_design <- lapply(blocks, function(b) {
  # Randomize accessions within block
  randomized <- sample(accessions)
  data.frame(
    range = b,
    plot = b * 100 + 1:15,
    row = 1:15,
    accession = randomized
  )
}) %>%
  bind_rows()

# View design
print(rcbd_design)

```

```{r}
CP2601_FBF <- rcbd_design %>% 
  mutate(experiment = "CP2601",
         location = "PDREC-F18",
         plot_name = paste(experiment, plot, sep = "_"),
         block = range,
         sort = c(1:60)) %>% 
  rename(accession_name = accession,
         plot_number = plot) %>% 
  select(experiment,
         location,
         accession_name,
         plot_name,
         plot_number,
         block,
         range,
         row,
         sort)

# Read in the file with the seedlots to use
SL_to_use <- read_csv("data/CP2601/2026_SL_to_use.csv") %>% 
  rename(seedlot_name = SL)

CP2601_FBF_final <- CP2601_FBF %>% 
  left_join(SL_to_use, by = "accession_name") 

# Write out the file
# write.csv(CP2601_FBF_final, "data/CP2601/CP2601_FBF.csv",row.names = FALSE, na = "")

```

Update the FBF to the correct seedlot 
```{r}
CP2601_FBF <- read_csv("data/CP2601/CP2601_FBF.csv") %>% 
  select(- seedlot_name)

# Read in the file with the seedlots to use
SL_to_use <- read_csv("data/CP2601/2026_SL_to_use.csv") %>% 
  rename(seedlot_name = SL)

CP2601_FBF_final2 <- CP2601_FBF %>% 
  left_join(SL_to_use, by = "accession_name") 

# Write out the file
# write.csv(CP2601_FBF_final2, "data/CP2601/CP2601_FBF.csv",row.names = FALSE, na = "")

```


```{r, echo=FALSE, fig.width=4, fig.height= 7}

FBF <- CP2601_FBF_final

acc.map <- 
  ggplot(FBF, aes(x = row, y = range)) +
  geom_tile(aes(fill = as.factor(block)), color = "black") +  
  geom_text(aes(label = accession_name), size = 3, color = "black", angle = 90) +  
  scale_fill_brewer(palette = "Dark2", name = "Block") +  
  scale_y_reverse(breaks = unique(FBF$range)) +  # Flip y-axis and show all row labels
  scale_x_continuous(breaks = unique(FBF$row)) +  # Ensure all range labels are shown
  theme_classic() +
  labs(
    title = "Field Map: CP2601",
    x = "Range",
    y = "Row"
  ) +
  theme(legend.position = "bottom")  # Place the legend at the bottom

plot.map <- 
  ggplot(FBF, aes(x = row, y = range)) +
  geom_tile(aes(fill = as.factor(block)), color = "black") +  
  geom_text(aes(label = plot_number), size = 3, color = "black", angle = 90) +  
  scale_fill_brewer(palette = "Dark2", name = "Block") +  
  scale_y_reverse(breaks = unique(FBF$range)) +  # Flip y-axis and show all row labels
  scale_x_continuous(breaks = unique(FBF$row)) +  # Ensure all range labels are shown
  theme_classic() +
  labs(
    title = "Field Map: CP2501",
    x = "Row",
    y = "Range"
  ) +
  theme(
    legend.position = "bottom")  


unique_id.map <- 
  ggplot(FBF, aes(x = row, y = range)) +
  geom_tile(aes(fill = as.factor(block)), color = "black") +  
  geom_text(aes(label = plot_name), size = 3, color = "black", angle = 90) +  
  scale_fill_brewer(palette = "Dark2", name = "Block") +  
  scale_y_reverse(breaks = unique(FBF$range)) +  # Flip y-axis and show all row labels
  scale_x_continuous(breaks = unique(FBF$row)) +  # Ensure all range labels are shown
  theme_classic() +
  labs(
    title = "Field Map: CP2601",
    x = "Row",
    y = "Range"
  ) +
  theme(
    legend.position = "bottom")

```

### Geno map
```{r,echo=FALSE}
plot(acc.map)

# ggsave("~/Documents/GitHub/cowpeas/data/CP2601/CP2601_geno_map.png", plot = acc.map, width = 9, height = 9, dpi = 300, units = "in")
```

### Plot map
```{r,echo=FALSE}
plot(plot.map)

# ggsave("~/Documents/GitHub/cowpeas/data/CP2601/CP2601_plot_map.png", plot = plot.map, width = 9, height = 6, dpi = 300, units = "in")
```

###Unique_id map
```{r}
plot(unique_id.map)

# ggsave("~/Documents/GitHub/cowpeas/data/CP2601/CP2601_unique_id_map.png", plot = unique_id.map, width = 9, height = 6, dpi = 300, units = "in")

